language: haskell

sudo: false
cache:
  directories:
  - $HOME/.stack/

before_install:
- mkdir -p ~/.local/bin/stack
- export PATH=~/.local/bin/stack:$PATH
- travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.6.0/stack-0.1.6.0-linux-x86_64.tar.gz | tar -xzf- -C ~/.local/bin/stack
- chmod a+x ~/.local/bin/stack/stack

install:
  - stack setup --no-terminal
  - stack build --no-terminal

script:
  - stack build --no-terminal
